"""Command line: python -m mnqbt <command> ...   (see README.md)"""

from __future__ import annotations

import argparse
import json
import logging
import re
import sys
from pathlib import Path

import numpy as np
import pandas as pd

from mnqbt.config import apply_overrides, get, load_config, load_yaml, VARIANTS_CONFIG
from mnqbt.data.store import raw_dir, results_dir, scratch_dir

log = logging.getLogger("mnqbt")
SYNTH_BANNER = (
    "> **SYNTHETIC DATA.** These numbers come from a random walk generated by `mnqbt synth`. "
    "They check that the pipeline runs and has no lookahead (a random walk must not show an edge). "
    "They say NOTHING about the real setup.\n"
)


def _out(cfg: dict, dataset: str) -> Path:
    return results_dir(cfg) / dataset


def _banner(dataset: str) -> str:
    return SYNTH_BANNER if dataset.startswith("synth") else ""


# ---------------------------------------------------------------------------- data
def cmd_synth(args, cfg):
    from mnqbt.data.build import build_dataset
    from mnqbt.data.synthetic import generate

    cfg = apply_overrides(cfg, {"instruments.splice_date": args.splice}) if args.splice else cfg
    raw = generate(args.start, args.end, seed=args.seed, splice_date=args.splice or None)
    report = _out(cfg, args.dataset) / "data_validation.md"
    build_dataset(cfg, raw, args.dataset, report_path=report)
    print(f"synthetic dataset '{args.dataset}' built; validation report: {report}")


def cmd_db_quote(args, cfg):
    from mnqbt.data.databento_fetch import plan_requests, quote

    q = quote(cfg, plan_requests(cfg, end=args.end, include_proxies=not args.no_proxies))
    print(q.to_string(index=False))
    print(f"TOTAL: ${q['usd'].sum():,.2f} for {q['gb'].sum():.2f} GB (nothing was downloaded)")


def cmd_db_download(args, cfg):
    from mnqbt.data.databento_fetch import download, plan_requests

    download(cfg, plan_requests(cfg, end=args.end, include_proxies=not args.no_proxies), max_cost=args.max_cost)


def cmd_import(args, cfg):
    from mnqbt.data import importers

    out = raw_dir(cfg, "import", args.root)
    out.mkdir(parents=True, exist_ok=True)
    for p in args.paths:
        if args.format == "ninjatrader":
            df = importers.read_ninjatrader(p, tz=args.tz, symbol=args.symbol)
        elif args.format == "firstrate":
            df = importers.read_firstrate(p, symbol=args.symbol, tz=args.tz)
        else:
            df = importers.read_generic_csv(p, symbol=args.symbol, tz=args.tz, ts_is_close=args.ts_is_close)
        target = out / (Path(p).stem.replace(" ", "_") + ".parquet")
        df.to_parquet(target)
        print(f"{p}: {len(df):,} bars, {df['symbol'].iloc[0]} -> {target}")


def cmd_build(args, cfg):
    from mnqbt.data.build import build_dataset
    from mnqbt.data.store import load_raw

    roots = [get(cfg, "instruments.traded"), get(cfg, "instruments.pair")]
    roots += [get(cfg, "instruments.proxies")[r] for r in roots] if not args.no_proxies else []
    raw = {}
    for r in roots:
        try:
            raw[r] = load_raw(cfg, args.source, r)
        except FileNotFoundError as exc:
            if r in roots[:2]:
                raise
            print(f"note: {exc} (continuing without proxy {r})")
    report = _out(cfg, args.dataset) / "data_validation.md"
    build_dataset(cfg, raw, args.dataset, report_path=report)
    print(f"dataset '{args.dataset}' built; validation report: {report}")


# ---------------------------------------------------------------------------- research
def _variant_cfg(cfg: dict, name: str) -> dict:
    from mnqbt.backtest.research import variant_plan

    for _, n, _, c in variant_plan(cfg, ("baseline", "add_one", "confirm", "full", "remove_one", "engine_checks")):
        if n == name or n.lstrip("+") == name:
            return c
    raise SystemExit(f"unknown variant {name!r}")


def cmd_charts(args, cfg):
    from mnqbt.backtest.research import load_features, period_bounds, run_one
    from mnqbt.reports.charts import plot_setup

    F = load_features(cfg, args.dataset)
    vcfg = _variant_cfg(cfg, args.variant)
    s, e = period_bounds(F, cfg, args.period)
    res = run_one(F, vcfg, args.variant, s, e)
    t = res.trades
    if t.empty:
        raise SystemExit("no trades to chart")
    rng = np.random.default_rng(args.seed)
    pick = []
    for reason in ("target", "stop", "flatten"):
        sub = t[t["exit_reason"] == reason]
        pick += list(rng.choice(sub.index, size=min(len(sub), max(1, args.n // 3)), replace=False)) if len(sub) else []
    out = _out(cfg, args.dataset) / "examples"
    lines = [f"# Example signals — `{args.variant}` ({args.dataset}, {args.period})", "", _banner(args.dataset),
             "Randomly sampled trades (winners, losers and time exits). Check each against how you would mark it by hand.", ""]
    for k, i in enumerate(sorted(pick)):
        row = t.loc[i]
        p = plot_setup(F, vcfg, row, out / f"example_{k + 1:02d}.png", tf=get(vcfg, "rules.smt.timeframe"))
        lines += [f"## Example {k + 1}", "", f"![example {k + 1}]({p.name})", "",
                  f"- placed {pd.Timestamp(row['placed_ns'], tz='UTC').tz_convert(get(cfg, 'project.timezone')):%Y-%m-%d %H:%M} ET, "
                  f"filled {pd.Timestamp(row['fill_ns'], tz='UTC').tz_convert(get(cfg, 'project.timezone')):%H:%M}, "
                  f"exit {pd.Timestamp(row['exit_ns'], tz='UTC').tz_convert(get(cfg, 'project.timezone')):%H:%M} ({row['exit_reason']})",
                  f"- entry {row['entry']:.2f}, stop {row['stop']:.2f}, target {row['target']:.2f}, risk {row['risk_pts']:.2f} pts, "
                  f"result {row['r_net']:+.2f}R net (${row['pnl_usd']:+.2f})",
                  f"- key level `{row['level']}`, confirmed by {row['confirm']}, SMT leader {row['smt_leader'] or '—'}, vol regime {row['vol_state']}, "
                  f"VWAP side {row['vwap_side']}, value area {row['va_loc']}, structure {row['structure_aligned']}", ""]
    (out / "README.md").write_text("\n".join(lines))
    print(f"{len(pick)} example charts in {out}")


def _verdicts(results) -> dict[str, str]:
    """Rough 'does it help' call vs the reference variant (baseline for add-one, full for remove-one)."""
    by = {r.name: r for r in results}
    ref_for = {"add_one": "baseline", "confirm": "baseline", "remove_one": "full", "engine_checks": "baseline", "full": "baseline"}
    out = {}
    for r in results:
        ref = by.get(ref_for.get(r.group, ""))
        if not ref or not r.summary.get("trades") or not ref.summary.get("trades"):
            continue
        a, b = r.trades["r_net"], ref.trades["r_net"]
        se = np.sqrt(a.var(ddof=1) / len(a) + b.var(ddof=1) / len(b)) if len(a) > 1 and len(b) > 1 else np.nan
        diff = a.mean() - b.mean()
        word = "no clear difference"
        if np.isfinite(se) and se > 0:
            if diff > 2 * se:
                word = "better"
            elif diff < -2 * se:
                word = "worse"
        out[r.name] = f"{diff:+.3f}R vs {ref.name} (±{2 * se:.3f}) → {word}"
    return out


def cmd_strategies(args, cfg):
    """STRATEGIES.md candidates on the development period only (no option to reach the holdout)."""
    import subprocess

    from mnqbt.reports import report as rp
    from mnqbt.strategies.run import load_dev, report, run_all

    F, mk = load_dev(cfg, args.dataset)
    names = args.only.split(",") if args.only else None
    res = run_all(cfg, F, mk, names=names, reps=args.reps, boot=args.boot, jobs=args.jobs)
    try:
        h = subprocess.run(["git", "log", "-1", "--format=%h", "--", "STRATEGIES.md"], capture_output=True, text=True,
                           cwd=Path(__file__).resolve().parents[1]).stdout.strip()
    except OSError:
        h = ""
    out = _out(cfg, args.dataset) / ("strategies_dev.md" if names is None else "strategies_dev_subset.md")
    rp.write(out, report(res, cfg, args.reps, args.boot, f" (last change to it: commit {h})" if h else ""))
    trade_dir = scratch_dir(cfg) / args.dataset / "strategies"   # git-ignored per-trade files
    trade_dir.mkdir(parents=True, exist_ok=True)
    for n, t in res.trades.items():
        t.drop(columns=[c for c in t.columns if c.endswith("_time")], errors="ignore").to_parquet(trade_dir / f"{n}.parquet")
    for s in res.strategies:
        m = res.stats[s.name]
        print(f"{s.name:20s} trades {m.get('trades', 0):6d}  avg R net {m.get('avg_r_net', float('nan')):+.3f}  "
              f"Holm p(edge) {m.get('holm_edge', float('nan')):.4f}  Holm p(random) {m.get('holm_random', float('nan')):.4f}")
    print(f"finalists: {res.finalists or 'none'}\nreport: {out}")


def cmd_patterns(args, cfg):
    """PATTERNS.md pattern search, one stage at a time; every test is logged."""
    from mnqbt.reports import report as rp
    from mnqbt.strategies.explore import log_report, out_dir, run_stage, stage_report

    res = run_stage(cfg, args.dataset, args.stage, reps=args.reps, unlock_final=args.unlock_final)
    d = out_dir(cfg, args.dataset)
    rp.write(d / f"{args.stage}.md", stage_report(res))
    rp.write(d / "README.md", log_report(cfg, args.dataset))
    trade_dir = scratch_dir(cfg) / args.dataset / "patterns" / args.stage   # git-ignored per-trade files
    trade_dir.mkdir(parents=True, exist_ok=True)
    for h, t in res.trades.items():
        t.drop(columns=[c for c in t.columns if c.endswith("_time")], errors="ignore").to_parquet(trade_dir / f"{h}.parquet")
    if res.note:
        print(res.note)
    for r in res.rows:
        eff = r.get("avg_r_net") if r["kind"] == "rule" else r.get("delta")
        print(f"{r['hypothesis']:3s} {r['instrument']} {r['split']:8s} trades {r['trades']:6d}  effect {eff:+.3f}  "
              f"p {r['p']:.4f}  adj {r.get('p_adj', float('nan')):.4f}  {'PASS' if r['passed'] else 'fail'}")
    print(f"report: {d / (args.stage + '.md')}")


def cmd_gex_download(args, cfg):
    """Fetch SqueezeMetrics' daily GEX CSV once (GAMMA.md).  Only run after the source was approved."""
    from mnqbt.data.gex import GEX_URL, download_gex, load_gex

    p = download_gex(cfg, force=args.force)
    g = load_gex(cfg)
    print(f"saved {GEX_URL} -> {p} ({p.stat().st_size:,} bytes, {len(g):,} dates, {g.index.min().date()} .. {g.index.max().date()})")


def cmd_gamma(args, cfg):
    """GAMMA.md study, one stage at a time; every test is logged in the pattern-search log."""
    from mnqbt.reports import report as rp
    from mnqbt.strategies.explore import log_report, out_dir
    from mnqbt.strategies.gamma_run import gamma_dir, run_stage, stage_report

    res = run_stage(cfg, args.dataset, args.stage, reps=args.reps, unlock_final=args.unlock_final)
    d = gamma_dir(cfg, args.dataset)
    rp.write(d / f"{args.stage}.md", stage_report(res))
    rp.write(out_dir(cfg, args.dataset) / "README.md", log_report(cfg, args.dataset))
    trade_dir = scratch_dir(cfg) / args.dataset / "gamma" / args.stage   # git-ignored per-trade files
    trade_dir.mkdir(parents=True, exist_ok=True)
    for h, t in res.trades.items():
        t.drop(columns=[c for c in t.columns if c.endswith("_time") or c in ("trail_ns", "trail_px")], errors="ignore").to_parquet(
            trade_dir / f"{h}.parquet")
    if res.note:
        print(res.note)
    for r in res.rows:
        eff = r.get("avg_r_net") if r["kind"] == "main" else r.get("delta")
        print(f"{r['hypothesis']:3s} {r['kind']:8s} {r['instrument']} {r['split']:8s} trades {r['trades']:6d}  "
              f"effect {(eff if eff is not None else float('nan')):+.3f}  p {r['p']:.4f}  adj {r.get('p_adj', float('nan')):.4f}  "
              f"{'PASS' if r['passed'] else 'fail'}")
    print(f"report: {d / (args.stage + '.md')}")


def cmd_suite(args, cfg):
    from mnqbt.backtest.research import load_features, period_bounds, run_suite
    from mnqbt.reports import report as rp
    from mnqbt.reports.charts import plot_by_year, plot_equity
    from mnqbt.reports.metrics import breakdown

    F = load_features(cfg, args.dataset)
    s, e = period_bounds(F, cfg, args.period)
    results = run_suite(F, cfg, s, e)
    out = _out(cfg, args.dataset)
    verdict = _verdicts(results)
    n_strategy = sum(1 for r in results if r.group != "engine_checks")
    L = [f"# Step 3 — does each piece help? ({args.dataset}, {args.period}: {s.date()} → {e.date()})", "", _banner(args.dataset)]
    L += [
        f"{n_strategy} strategy configurations were run (plus {len(results) - n_strategy} engine-sensitivity runs). "
        "No parameter was tuned: every variant uses config/default.yaml and changes only the piece named.",
        "",
        "- **avg R net**: average result per trade in units of initial risk, after commission, fees and slippage.",
        "- **95% CI**: bootstrap confidence interval of avg R, resampling trades, and resampling whole trading days (safer when trades cluster).",
        "- **PF**: gross profit ÷ gross loss in dollars, after costs. **max DD**: largest peak-to-trough fall of closed-trade equity.",
        "- Rows marked ⚠ have fewer than "
        f"{get(cfg, 'research.min_trades_warning')} trades: treat them as anecdotes.",
        "",
        rp.summary_table(results),
        "",
        "### Comparison to reference (difference in avg R net, ± ~2 standard errors)",
        "",
        "Overlapping trade sets make this rough; 'better/worse' needs the gap to exceed about two standard errors.",
        "",
    ]
    L += [f"- **{k}**: {v}" for k, v in verdict.items()]
    L.append("")
    base = next(r for r in results if r.name == "baseline")
    full = next(r for r in results if r.name == "full")
    plot_equity({"baseline": base.trades, "full": full.trades}, out / "equity_baseline_full.png", "Cumulative net R — baseline vs full setup")
    L += ["![equity](equity_baseline_full.png)", ""]
    if not base.trades.empty:
        yb = breakdown(base.trades, "year")
        plot_by_year(yb, out / "baseline_by_year.png", "Baseline: average net R per trade, by year")
        L += ["![baseline by year](baseline_by_year.png)", ""]
    detail_keys = ["session", "weekday", "year"]
    all_keys = ["session", "weekday", "year", "direction", "vol regime", "key level", "confirmation", "SMT leader", "VWAP side", "value area",
                "structure", "news day", "target"]
    for r in results:
        L += [f"## {r.name}", ""]
        if r.overrides:
            L += ["Overrides: `" + json.dumps(r.overrides) + "`", ""]
        L += ["<details><summary>Signal funnel (how many candidates each rule removed)</summary>", "", rp.funnel_md(r.funnel), "", "</details>", ""]
        if r.trades.empty:
            L += ["_No trades._", ""]
            continue
        L += [rp.breakdown_md(r.trades, all_keys if r.name in ("baseline", "full") else detail_keys), ""]
    rp.write(out / "step3_variants.md", "\n".join(L))
    trade_dir = scratch_dir(cfg) / args.dataset / "trades"  # git-ignored: per-trade files for your own analysis
    trade_dir.mkdir(parents=True, exist_ok=True)
    for r in results:
        if not r.trades.empty:
            slug = re.sub(r"[^a-z0-9]+", "_", r.name.lower().replace("+", "plus ").replace("−", "minus ")).strip("_")
            r.trades.drop(columns=[c for c in r.trades.columns if c.endswith("_time")]).to_parquet(trade_dir / f"{slug}.parquet")
    print(rp.summary_table(results))
    print(f"\nper-trade files: {trade_dir}")
    print(f"\nreport: {out / 'step3_variants.md'}")


def cmd_walkforward(args, cfg):
    from mnqbt.backtest.engine import EngineSettings
    from mnqbt.backtest.random_bench import random_benchmark
    from mnqbt.backtest.research import grid_combos, load_features, period_bounds, run_one, walk_forward
    from mnqbt.reports import report as rp
    from mnqbt.reports.charts import plot_benchmark
    from mnqbt.reports.metrics import summarize

    F = load_features(cfg, args.dataset)
    s, e = period_bounds(F, cfg, "dev")
    out = _out(cfg, args.dataset)
    wf, oos, tbl = walk_forward(F, cfg)
    n_combos = len(grid_combos(cfg))
    L = [f"# Step 4 — tuning, walk-forward, stability, random benchmark ({args.dataset})", "", _banner(args.dataset),
         f"Development period: {s.date()} → {e.date()}. The holdout ({get(cfg, 'research.holdout_start')} →) is NOT used here.", "",
         f"## Tuning grid: {n_combos} combinations tried (baseline setup)", "",
         "Pre-declared in config (`research.tuning_grid`); nothing else was tuned. Every combination is listed — "
         "the best of N noisy results is biased upward, so read the spread, not the maximum.", ""]
    cols = [c for c in tbl.columns if c not in ("combo", "_trades", "warning", "eligible") and not c.startswith("ci_day")]
    show = tbl[[c for c in cols if c in ("fvg_fraction", "r_multiple", "max_minutes_smt_to_fvg", "trades", "win_rate", "avg_r_net",
                                        "ci_low", "ci_high", "profit_factor", "net_pnl_usd", "max_dd_r")]]
    L += [rp.df_to_md(show.set_index(show.columns[0]), {"win_rate": "{:.1%}", "net_pnl_usd": "{:,.0f}", "trades": "{:.0f}"}), ""]
    L += ["## Anchored walk-forward (inside the development period)", "",
          "Each year is tested with the combination that looked best on all earlier years; the table shows whether that choice held up.", "",
          rp.df_to_md(wf.set_index("test_year") if len(wf) else wf, {"test_trades": "{:.0f}"}), ""]
    if len(oos):
        so = summarize(oos)
        L += [f"Stitched walk-forward out-of-sample: **{so['trades']} trades, avg R net {so['avg_r_net']:+.3f} "
              f"[95% CI {so['ci_low']:+.3f}, {so['ci_high']:+.3f}]**, win rate {so['win_rate']:.1%}. {so['warning']}", ""]
    base = run_one(F, cfg, "baseline", s, e)
    L += ["## Stability of the (untuned) baseline", "", rp.breakdown_md(base.trades, ["year", "vol regime", "session"]), ""]
    st = EngineSettings.from_cfg(cfg)
    L += ["## Random-entry benchmark", "",
          "Each real order is replayed on a random day at the same time of day: same order type, same limit distance from the "
          "market (in ATRs), same wait, stop (in ATRs), target (in R), fill rules, exits and costs — only the signal is missing. "
          "If the strategy's avg R is not clearly to the right of this distribution, the signals add nothing.", ""]
    variants = {"baseline": cfg}
    v = load_yaml(VARIANTS_CONFIG)
    variants["full"] = apply_overrides(cfg, v["full"])
    for name, vcfg in variants.items():
        res = base if name == "baseline" else run_one(F, vcfg, name, s, e)
        if res.trades.empty:
            L += [f"- {name}: no trades", ""]
            continue
        bm = random_benchmark(F, vcfg, res.trades, s, e, int(get(cfg, "research.random_benchmark_reps")), st, seed=1)
        plot_benchmark(bm["dist"], bm["strategy"], out / f"benchmark_{name}.png", f"{name}: strategy vs {len(bm['dist'])} random-entry runs")
        L += [f"**{name}**: strategy {bm['strategy']:+.3f}R vs random mean {bm['bench_mean']:+.3f}R "
              f"(5–95%: {bm['bench_p05']:+.3f} … {bm['bench_p95']:+.3f}); one-sided p = {bm['p_value']:.3f}", "",
              f"![benchmark {name}](benchmark_{name}.png)", ""]
    rp.write(out / "step4_walkforward.md", "\n".join(L))
    print(f"report: {out / 'step4_walkforward.md'}")


def cmd_holdout(args, cfg):
    from mnqbt.backtest.random_bench import random_benchmark
    from mnqbt.backtest.engine import EngineSettings
    from mnqbt.backtest.research import holdout_log_path, load_features, log_holdout, period_bounds, run_one
    from mnqbt.reports import report as rp

    vcfg = _variant_cfg(cfg, args.variant)
    if args.set:
        vcfg = apply_overrides(vcfg, {k: json.loads(v) for k, v in (kv.split("=", 1) for kv in args.set)})
    F = load_features(cfg, args.dataset)
    s, e = period_bounds(F, cfg, "holdout")
    prior = holdout_log_path(cfg, args.dataset)
    n_prior = sum(1 for _ in open(prior)) if prior.exists() else 0
    if n_prior and not args.i_understand:
        raise SystemExit(f"the holdout has already been used {n_prior} time(s) (see {prior}). Re-running it is how holdouts stop "
                         "being holdouts. Pass --i-understand to run anyway; it will be logged.")
    res = run_one(F, vcfg, args.variant, s, e)
    log_holdout(cfg, args.dataset, args.variant, {"set": args.set or []}, res.summary, args.note or "")
    out = _out(cfg, args.dataset)
    L = [f"# Holdout test — `{args.variant}` ({s.date()} → {e.date()})", "", _banner(args.dataset),
         f"Holdout evaluations so far (including this one): {n_prior + 1}. Logged in results/{args.dataset}/holdout_log.jsonl.", "",
         rp.summary_table([res]), ""]
    if not res.trades.empty:
        bm = random_benchmark(F, vcfg, res.trades, s, e, int(get(cfg, "research.random_benchmark_reps")), EngineSettings.from_cfg(cfg))
        L += [f"Random-entry benchmark: strategy {bm['strategy']:+.3f}R vs random {bm['bench_mean']:+.3f}R, p = {bm['p_value']:.3f}", "",
              rp.breakdown_md(res.trades, ["year", "session", "weekday"])]
    rp.write(out / f"holdout_{args.variant}.md", "\n".join(L))
    print(rp.summary_table([res]))


def main(argv=None):
    ap = argparse.ArgumentParser(prog="mnqbt", description=__doc__)
    ap.add_argument("--config", default=None, help="YAML config (default config/default.yaml)")
    ap.add_argument("-v", "--verbose", action="store_true")
    sub = ap.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("synth", help="generate a synthetic dataset (for tests / pipeline checks)")
    p.add_argument("--start", default="2019-01-02")
    p.add_argument("--end", default="2022-12-30")
    p.add_argument("--seed", type=int, default=7)
    p.add_argument("--splice", default="", help="splice date to also exercise NQ/ES->MNQ/MES (e.g. 2020-07-01)")
    p.add_argument("--dataset", default="synthetic")
    p.set_defaults(fn=cmd_synth)

    for name, fn in (("db-quote", cmd_db_quote), ("db-download", cmd_db_download)):
        p = sub.add_parser(name, help="Databento: " + ("price quote only (free)" if name == "db-quote" else "download (asks for nothing, obeys --max-cost)"))
        p.add_argument("--end", default=None, help="exclusive end date (default today)")
        p.add_argument("--no-proxies", action="store_true", help="skip NQ/ES history before the splice")
        if name == "db-download":
            p.add_argument("--max-cost", type=float, required=True, help="refuse to download if the quote exceeds this (USD)")
        p.set_defaults(fn=fn)

    p = sub.add_parser("import", help="import vendor export files as raw per-contract bars")
    p.add_argument("--format", choices=["ninjatrader", "firstrate", "csv"], required=True)
    p.add_argument("--root", required=True, help="MNQ, MES, NQ or ES")
    p.add_argument("--symbol", default=None, help="contract symbol, e.g. MNQH4 (inferred for NinjaTrader file names)")
    p.add_argument("--tz", default="America/New_York", help="time zone of the file's timestamps")
    p.add_argument("--ts-is-close", action="store_true", help="generic csv: timestamps mark bar close")
    p.add_argument("paths", nargs="+")
    p.set_defaults(fn=cmd_import)

    p = sub.add_parser("build", help="continuous contracts + validation report")
    p.add_argument("--source", default="databento", help="raw source folder: databento | import")
    p.add_argument("--dataset", default="real")
    p.add_argument("--no-proxies", action="store_true")
    p.set_defaults(fn=cmd_build)

    p = sub.add_parser("charts", help="example signal charts for visual checking")
    p.add_argument("--dataset", default="real")
    p.add_argument("--variant", default="baseline")
    p.add_argument("--period", default="dev", choices=["dev", "all"])
    p.add_argument("--n", type=int, default=9)
    p.add_argument("--seed", type=int, default=0)
    p.set_defaults(fn=cmd_charts)

    p = sub.add_parser("patterns", help="PATTERNS.md pattern search: explore -> validate -> mes -> final")
    p.add_argument("--stage", required=True, choices=["explore", "validate", "mes", "final"])
    p.add_argument("--dataset", default="real")
    p.add_argument("--reps", type=int, default=1000, help="random-entry benchmark runs (explore passes only)")
    p.add_argument("--unlock-final", action="store_true", help="required for --stage final; only when told to")
    p.set_defaults(fn=cmd_patterns)

    p = sub.add_parser("gex-download", help="fetch SqueezeMetrics' free daily GEX CSV once (GAMMA.md)")
    p.add_argument("--force", action="store_true", help="fetch again even if the file exists")
    p.set_defaults(fn=cmd_gex_download)

    p = sub.add_parser("gamma", help="GAMMA.md gamma-regime study: explore -> validate -> mes -> final")
    p.add_argument("--dataset", default="real")
    p.add_argument("--stage", choices=["explore", "validate", "mes", "final"], required=True)
    p.add_argument("--reps", type=int, default=1000, help="random-entry benchmark runs (explore passes only)")
    p.add_argument("--unlock-final", action="store_true", help="allow the final test (only when told to)")
    p.set_defaults(fn=cmd_gamma)

    p = sub.add_parser("strategies", help="STRATEGIES.md candidates, development period only")
    p.add_argument("--dataset", default="real")
    p.add_argument("--only", default=None, help="comma-separated strategy names (default: all)")
    p.add_argument("--reps", type=int, default=1000, help="random-entry benchmark runs")
    p.add_argument("--boot", type=int, default=10000, help="bootstrap resamples for p (edge)")
    p.add_argument("--jobs", type=int, default=4)
    p.set_defaults(fn=cmd_strategies)

    p = sub.add_parser("suite", help="Step 3: baseline, add-one, full, remove-one")
    p.add_argument("--dataset", default="real")
    p.add_argument("--period", default="dev", choices=["dev", "all"])
    p.set_defaults(fn=cmd_suite)

    p = sub.add_parser("walkforward", help="Step 4: grid, anchored walk-forward, stability, random benchmark (dev period only)")
    p.add_argument("--dataset", default="real")
    p.set_defaults(fn=cmd_walkforward)

    p = sub.add_parser("holdout", help="Step 4: ONE-TIME test on the holdout period (logged)")
    p.add_argument("--dataset", default="real")
    p.add_argument("--variant", default="baseline")
    p.add_argument("--set", nargs="*", help="extra overrides key=json, e.g. setup.target.r_multiple=3.0")
    p.add_argument("--note", default="")
    p.add_argument("--i-understand", action="store_true", help="allow re-using the holdout (still logged)")
    p.set_defaults(fn=cmd_holdout)

    args = ap.parse_args(argv)
    logging.basicConfig(level=logging.INFO if args.verbose else logging.WARNING, format="%(levelname)s %(name)s: %(message)s")
    cfg = load_config(args.config)
    args.fn(args, cfg)


if __name__ == "__main__":
    sys.exit(main())
